### PR TITLE
setting up a mouse up handler on the checkboxes

### PR DESCRIPTION
**Pull request by SirZach**
#4 not sure if this is the best pattern. there's some difficulty in this procedure since there are nested components instead of the outer component yielding and letting the developer fill in how they want the option components to be used.

### CODE REVIEW

**Comment by RSSchermer** [comment]
Thanks a lot for making a pull request!

There's a bit of a problem with going with the `mouseUp` event for this: it kind of breaks keyboard interaction (tab + space bar) with the checkboxes. The solution to that would be to use the `change` event instead. That has a downside to, in that now also "programmatic changes" to the checkbox value will send the event. You could also consider that a feature though, and in any case, I think the fact that it works with keyboard as well would make that worth it anyway.

If that is an acceptable solution though, I think we can simplify things a lot, because listening for individual checkbox changes is basically equivalent to observing the selection itself for a change. Something like this on the container component might work:

```js
watchSelection: function () {
  this.sendAction('action',  this.get('selection'));
}.observes('selection').on('init')
```

Curious what your thoughts on all this are and would this work for your use-case?

**Comment by SirZach** [comment]
Nice thoughts on keeping the keyboard interaction intact. I had originally
set up a click handler but it fires twice so I switched over to a mouseUp
and that alleviated the problem.

The problem with observing the selection is now your action doesn't receive
the item you just clicked on and instead gets the entire collection which
would be easy to get without it being a parameter. I think there's a
structural problem to the way this is set up with having the template of
the selection component reference the item components instead of yielding
and letting the developer plug in the item components where they could put
an action handler directly on it.  But in order to pull that off, the
developer now has to set up his own each loop so why use this addon at all?
Maybe something like block params gets it one step closer.

**Comment by RSSchermer** [comment]
I think the "observing the selection" way of doing it is good to add to the component anyway, in light of ember 2.0 philosophy of "data down, actions up" (even though using `mut` for these kinds of form elements is probably more convenient, the option to rely only on actions should be there), so I'll look into adding that anyway as the primary action of the parent component.

As to customizing the individual items, I think that block params and htmlbars may provide a solution. I think the main way of using the addon should remain using just the container component like so:

```hbs
<multiselect-checkboxes options=users labelProperty='name' selection=selectedUsers>
```

But perhaps an alternative way of use can be achieved that allows more customization of the individual options, something like this perhaps:
```hbs
<multiselect-checkboxes options=users labelProperty='name' selection=selectedUsers as |value label|>
  <label>
    <multiselect-checkbox value=value>
    {{label}}
  </label>
</multiselect-checkboxes>
```
You could then add actions to any element you like.

**Comment by SirZach** [comment]
I like the idea of having that variability.

With regards to your second example, do you think <code>multiselect-checkbox</code>'s tag should be <code>label</code> by default to encourage proper use of checkboxes?

**Comment by RSSchermer** [comment]
Perhaps you could do both:

```hbs
<multiselect-checkboxes options={{users}} labelProperty='name' selection={{selectedUsers}} as |value label|>
    <multiselect-checkbox-option value={{value}}>{{label}}</multiselect-checkbox-option>
</multiselect-checkboxes>
```
As sugar for:
```hbs
<multiselect-checkboxes options={{users}} labelProperty='name' selection={{selectedUsers}} as |value label|>
  <label>
    <multiselect-checkbox value={{value}}>
    {{label}}
  </label>
</multiselect-checkboxes>
```
That's a little more messy to document though.

**Comment by SirZach** [comment]
This feels like a stylistic decision that I'll leave up to you. Both are viable to me.

**Comment by RSSchermer** [comment]
As of Ember 1.13, it finally became possible to implement this in a nice way. I just published 0.4.0 which implements passing custom template blocks as discussed. The final syntax has become:

```handlebars
{{#multiselect-checkboxes options=users labelProperty='name' selection=selectedUsers as |label isSelected|}}
  <li>
    <label>
      {{input type="checkbox" checked=isSelected}}
      {{label}}
    </label>
  </li>
{{/multiselect-checkboxes}}
```

**Comment by RSSchermer** [comment]
Closing this for now. I think being able to pass a custom block as of 0.4.x should address this. If there are still issues I'd be happy to reopen.

**Pull request closed without merging**
